# Generated by Django 4.2.2 on 2023-07-12 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('descriptoin', models.TextField(max_length=500, verbose_name='Описание')),
                ('compound', models.TextField(max_length=500, verbose_name='Состав')),
                ('image', models.ImageField(upload_to='media', verbose_name='Фото')),
                ('categoty', models.CharField(max_length=100, verbose_name='Категория')),
            ],
        ),
    ]
