# Generated by Django 4.2.2 on 2023-07-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AddField(
            model_name='product',
            name='cost',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='categoty',
            field=models.CharField(choices=[('BM', 'Блюда на мангале'), ('HL', 'Хлеб'), ('TP', 'Торты и пирожные'), ('PM', 'Пироги мясные'), ('PO', 'Пироги с овощной начинкой'), ('ZM', 'Запекание мяса'), ('ZP', 'Запекание птицы'), ('ZR', 'Запекание рыбы'), ('ZH', 'Жаркое с овощами'), ('SA', 'Салаты'), ('RO', 'Рогалики, булки и печенье'), ('MA', 'Изделия с маковой начинкой'), ('BL', 'Блины'), ('PE', 'Пельмени и вареники'), ('MI', 'Молоко, сметана, масло и творог'), ('HO', 'Мёд'), ('HD', 'Горячие напитки')], max_length=100, verbose_name='Категория'),
        ),
    ]
