# Generated by Django 4.2.2 on 2023-07-12 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_options_product_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cost',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
