# Generated by Django 4.2.2 on 2023-07-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='compound',
            field=models.TextField(default='--', max_length=500, verbose_name='Состав'),
        ),
        migrations.AlterField(
            model_name='product',
            name='descriptoin',
            field=models.TextField(default='--', max_length=500, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='img/', verbose_name='Фото'),
        ),
    ]
